### ISSUE TITLE
Nullpointer

### ISSUE THREAD

**Issue by KoxSosen** [HahotaMC/ProxyQueue#1]
[08:02:04 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[08:02:04 ERROR]: #1:

java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
        at java.nio.file.Files.copy(Files.java:3035) ~[?:?]
        at me.blackgoldytc.proxyqueue.ProxyQueues.createFile(ProxyQueues.java:98) ~[?:?]
        at me.blackgoldytc.proxyqueue.ProxyQueues.onProxyInitialize(ProxyQueues.java:52) ~[?:?]
        at net.kyori.event.asm.generated.fef22430bc.ProxyQueues-onProxyInitialize-ProxyInitializeEvent-11.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velo.jar:1.1.4]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velo.jar:1.1.4]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:137) ~[velo.jar:1.1.4]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:119) ~[velo.jar:1.1.4]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by KoxSosen** [comment]
Will not be fixed.
